project/users/models.py
from .. import db
from flask.ext.security import Security, SQLAlchemyUserDatastore, UserMixin, RoleMixin

roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))
    connections = db.relationship('Connection', backref=db.backref('user', lazy='joined'), cascade="all")
    estimates = db.relationship("Estimate", backref='user')

class Connection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    provider_id = db.Column(db.String(255))
    provider_user_id = db.Column(db.String(255))
    access_token = db.Column(db.String(255))
    secret = db.Column(db.String(255))
    display_name = db.Column(db.String(255))
    full_name = db.Column(db.String(255))
    profile_url = db.Column(db.String(512))
    image_url = db.Column(db.String(512))
    rank = db.Column(db.Integer)

project/users/forms.py
from flask import current_app
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, ValidationError
from wtforms.validators import Required, Email, Length, Regexp, EqualTo

class UniqueUser(object):
    def __init__(self, message="User exists"):
        self.message = message

    def __call__(self, form, field):
        if current_app.security.datastore.find_user(email=field.data):
            raise ValidationError(self.message)


validators = {
    'email': [
        Required(),
        Email(),
        UniqueUser(message='Email address is associated with '
                           'an existing account')
    ],
    'password': [
        Required(),
        Length(min=6, max=50),
        EqualTo('confirm', message='Passwords must match'),
        Regexp(r'[A-Za-z0-9@#$%^&+=]',
               message='Password contains invalid characters')
    ]
}


class RegisterForm(Form):
    email = TextField('Email', validators['email'])
    password = PasswordField('Password', validators['password'], )
    confirm = PasswordField('Confirm Password')

project/users/__init__.py
from flask import Blueprint
from flask.ext.security import Security, SQLAlchemyUserDatastore

users = Blueprint('users', __name__, template_folder='templates')

from . import models, views, forms

project/users/views.py
from flask import render_template, request, current_app, session, flash, redirect, url_for
from flask.ext.security import login_required, current_user, login_user, LoginForm
from flask.ext.social.utils import get_provider_or_404
from flask.ext.social.views import connect_handler
from . import users
from .models import User, Role
from .forms import RegisterForm

@users.route('/profile')
@login_required
def profile():
    return render_template(
        'profile.html',
        content='Profile Page',
        facebook_conn=current_app.social.facebook.get_connection())

@users.route('/register', methods=['GET', 'POST'])
@users.route('/register/<provider_id>', methods=['GET', 'POST'])
def register(provider_id=None):
    if current_user.is_authenticated():
        return redirect(request.referrer or '/')

    form = RegisterForm()

    if provider_id:
        provider = get_provider_or_404(provider_id)
        connection_values = session.get('failed_login_connection', None)
    else:
        provider = None
        connection_values = None

    print "just before form.validate_on_submit"

    if form.validate_on_submit():
        ds = current_app.security.datastore
        user = ds.create_user(email=form.email.data, password=form.password.data)
        ds.commit()

        # See if there was an attempted social login prior to registering
        # and if so use the provider connect_handler to save a connection
        connection_values = session.pop('failed_login_connection', None)

        print connection_values

        if connection_values:
            connection_values['user_id'] = user.id
            connect_handler(connection_values, provider)

        print user

        if login_user(user):
            ds.commit()
            flash('Account created successfully', 'info')
            return redirect(url_for('users.profile'))

        return render_template('thanks.html', user=user)

    login_failed = int(request.args.get('login_failed', 0))

    return render_template('register.html',
                           form=form,
                           provider=provider,
                           login_failed=login_failed,
                           connection_values=connection_values)

project/users/templates/_macros.html
{% macro render_field(field) %}
  {{ field.label }}
  {% if field.errors %}
    <ul class="errors">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  {{ field(**kwargs)|safe }}
{% endmacro %}

project/users/templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="container">
{{current_user.email}}
{% macro show_provider_button(provider_id, display_name, conn) %}
    {% if conn %}
    <form action="{{ url_for('social.remove_connection', provider_id=conn.provider_id, provider_user_id=conn.provider_user_id) }}" method="DELETE">
      <input type="submit" value="Disconnect {{ display_name }}" />
    </form>
    {% else %}
    <form action="{{ url_for('social.connect', provider_id=provider_id) }}" method="POST">
      <input type="submit" value="Connect {{ display_name }}" />
    </form>
    {% endif %}
{% endmacro %}

{{ show_provider_button('facebook', 'facebook', facebook_conn) }}
</div>
{% endblock %}

project/users/templates/register.html
{% extends "base.html" %}

{% from '_macros.html' import render_field %}

{% macro social_register(provider_id, display_name) %}
  <form action="{{ url_for('social.login', provider_id=provider_id) }}" method="POST">
    <button type="submit" class="btn btn-primary btn-large">Register with {{ display_name }}</button>
  </form>
{% endmacro %}

{% block content %}
<div class="page-header">
<h1>Register<h1>
</div>
{% if login_failed %}
<h3>Register with your {{ provider.name }} account: {{ connection_values['display_name'] }}</h3>
{% endif %}
<div class="row content">
  <div class="aspan4 aoffset1">
    <form class="well" action="{{ url_for('users.register', provider_id=provider.id if provider else None) }}" method="POST">
      {{ form.hidden_tag() }}
      {{ render_field(form.email) }}
      {{ render_field(form.password) }}
      {{ render_field(form.confirm) }}
      <button type="submit" class="btn btn-primary btn-large">Register</button>
    </form>
  </div>
</div>
  {% if not login_failed %}
    <h3>OR</h3>
    {{ social_register('google', 'google' )}}
    {{ social_register('facebook', 'Facebook' )}}
  {% endif %}
</div>
{% endblock %}